###etsing 
post http://localhost:8000/api/v1/users
Content-Type: application/json

{
    "name":"tokey",
    "email":"a111@a111.com",
    "password":"123"
}

###etsing 
get http://localhost:8000/api/v1/users/all


###etsing 
DELETE  http://localhost:8000/api/v1/users?id=97





